### 1 Population
library(mapplots)
library(rworldmap)
data(countriesLow)
plot(countriesLow)
coo <- read.table("sampling_data.csv", h = F, stringsAsFactors = F, row.names = NULL, sep = ",")
my_dir <- getwd()
file <- list.files(path=my_dir, pattern="*meanQ", full.names=TRUE, recursive=FALSE)
a <- read.table(file)
gabri <- cbind(a$V1)
gabri <- as.numeric(gabri)
n <- length(a$V1)
gabri_2 <- c(rep("pop1",n))
gabri_2 <- as.factor(gabri_2)
lon <- rep(coo$V7,1)
lat <- rep(coo$V6,1)
# added extra digit to duplicate coordinates to avoid removal of records
xyz <- make.xyz(lon, lat, gabri,gabri_2)
pdf("map.pdf")
plot(countriesLow, xlim= c(min(coo$V7-5),max(coo$V7 + 5)), ylim = c(min(coo$V6-5),max(coo$V6+5)))
COL <- c("#999999", "#E69F00", "#56B4E9", "#009E73","#F0E442", "#0072B2", "#D55E00", "#CC79A7", "black",)
draw.pie(xyz$x, xyz$y, xyz$z, radius = 0.25, col = COL)
box(col="gray")
dev.off()



### 2 Populations
library(mapplots)
library(rworldmap)
data(countriesLow)
plot(countriesLow)
coo <- read.table("sampling_data.csv", h = F, stringsAsFactors = F, row.names = NULL, sep = ",")
my_dir <- getwd()
file <- list.files(path=my_dir, pattern="*meanQ", full.names=TRUE, recursive=FALSE)
a <- read.table(file)
gabri <- cbind(a$V1,a$V2)
gabri <- as.numeric(gabri)
n <- length(a$V1)
gabri_2 <- c(rep("pop1",n), rep("pop2",n))
gabri_2 <- as.factor(gabri_2)
lon <- rep(coo$V7,2)
lat <- rep(coo$V6,2)
# added extra digit to duplicate coordinates to avoid removal of records
xyz <- make.xyz(lon, lat, gabri,gabri_2)
pdf("map.pdf")
plot(countriesLow, xlim= c(min(coo$V7-5),max(coo$V7 + 5)), ylim = c(min(coo$V6-5),max(coo$V6+5)))
COL <- c("#999999", "#E69F00", "#56B4E9", "#009E73","#F0E442", "#0072B2", "#D55E00", "#CC79A7", "black")
draw.pie(xyz$x, xyz$y, xyz$z, radius = 0.25, col = COL)
box(col="gray")
dev.off()



#### 3 Populations
library(mapplots)
library(rworldmap)
data(countriesLow)
plot(countriesLow)
coo <- read.table("sampling_data.csv", h = F, stringsAsFactors = F, row.names = NULL, sep = ",")
my_dir <- getwd()
file <- list.files(path=my_dir, pattern="*meanQ", full.names=TRUE, recursive=FALSE)
a <- read.table(file)
gabri <- cbind(a$V1,a$V2,a$V3)
gabri <- as.numeric(gabri)
n <- length(a$V1)
gabri_2 <- c(rep("pop1",n), rep("pop2", n), rep("pop3",n))
gabri_2 <- as.factor(gabri_2)
lon <- rep(coo$V7,3)
lat <- rep(coo$V6,3)
# added extra digit to duplicate coordinates to avoid removal of records
xyz <- make.xyz(lon, lat, gabri,gabri_2)
pdf("map.pdf")
plot(countriesLow, xlim= c(min(coo$V7-5),max(coo$V7 + 5)), ylim = c(min(coo$V6-5),max(coo$V6+5)))
COL <- c("#999999", "#E69F00", "#56B4E9", "#009E73","#F0E442", "#0072B2", "#D55E00", "#CC79A7", "black")
draw.pie(xyz$x, xyz$y, xyz$z, radius = 0.25, col = COL)
box(col="gray")
dev.off()



### 4 Populations
library(mapplots)
library(rworldmap)
data(countriesLow)
plot(countriesLow)
coo <- read.table("sampling_data.csv", h = F, stringsAsFactors = F, row.names = NULL, sep = ",")
my_dir <- getwd()
file <- list.files(path=my_dir, pattern="*meanQ", full.names=TRUE, recursive=FALSE)
a <- read.table(file)
gabri <- cbind(a$V1,a$V2,a$V3,a$V4)
gabri <- as.numeric(gabri)
n <- length(a$V1)
gabri_2 <- c(rep("pop1",n), rep("pop2", n), rep("pop3",n),rep("pop4",n))
gabri_2 <- as.factor(gabri_2)
lon <- rep(coo$V7,4)
lat <- rep(coo$V6,4)
# added extra digit to duplicate coordinates to avoid removal of records
xyz <- make.xyz(lon, lat, gabri,gabri_2)
pdf("map.pdf")
plot(countriesLow, xlim= c(min(coo$V7-5),max(coo$V7 + 5)), ylim = c(min(coo$V6-5),max(coo$V6+5)))
COL <- c("#999999", "#E69F00", "#56B4E9", "#009E73","#F0E442", "#0072B2", "#D55E00", "#CC79A7", "black")
draw.pie(xyz$x, xyz$y, xyz$z, radius = 0.25, col = COL)
box(col="gray")
dev.off()



### 5 Populations
library(mapplots)
library(rworldmap)
data(countriesLow)
plot(countriesLow)
coo <- read.table("sampling_data.csv", h = F, stringsAsFactors = F, row.names = NULL, sep = ",")
my_dir <- getwd()
file <- list.files(path=my_dir, pattern="*meanQ", full.names=TRUE, recursive=FALSE)
a <- read.table(file)
gabri <- cbind(a$V1,a$V2,a$V3,a$V4,a$V5)
gabri <- as.numeric(gabri)
n <- length(a$V1)
gabri_2 <- c(rep("pop1",n), rep("pop2", n), rep("pop3",n),rep("pop4",n),rep("pop5",n))
gabri_2 <- as.factor(gabri_2)
lon <- rep(coo$V7,5)
lat <- rep(coo$V6,5)
# added extra digit to duplicate coordinates to avoid removal of records
xyz <- make.xyz(lon, lat, gabri,gabri_2)
pdf("map.pdf")
plot(countriesLow, xlim= c(min(coo$V7-5),max(coo$V7 + 5)), ylim = c(min(coo$V6-5),max(coo$V6+5)))
COL <- c("#999999", "#E69F00", "#56B4E9", "#009E73","#F0E442", "#0072B2", "#D55E00", "#CC79A7", "black")
draw.pie(xyz$x, xyz$y, xyz$z, radius = 0.25, col = COL)
box(col="gray")
dev.off()



### 6 Populations
library(mapplots)
library(rworldmap)
data(countriesLow)
plot(countriesLow)
coo <- read.table("sampling_data.csv", h = F, stringsAsFactors = F, row.names = NULL, sep = ",")
my_dir <- getwd()
file <- list.files(path=my_dir, pattern="*meanQ", full.names=TRUE, recursive=FALSE)
a <- read.table(file)
gabri <- cbind(a$V1,a$V2,a$V3,a$V4,a$V5,a$V6)
gabri <- as.numeric(gabri)
n <- length(a$V1)
gabri_2 <- c(rep("pop1",n), rep("pop2", n), rep("pop3",n),rep("pop4",n),rep("pop5",n),rep("pop6",n))
gabri_2 <- as.factor(gabri_2)
lon <- rep(coo$V7,6)
lat <- rep(coo$V6,6)
# added extra digit to duplicate coordinates to avoid removal of records
xyz <- make.xyz(lon, lat, gabri,gabri_2)
pdf("map.pdf")
plot(countriesLow, xlim= c(min(coo$V7-5),max(coo$V7 + 5)), ylim = c(min(coo$V6-5),max(coo$V6+5)))
COL <- c("#999999", "#E69F00", "#56B4E9", "#009E73","#F0E442", "#0072B2", "#D55E00", "#CC79A7", "black")
draw.pie(xyz$x, xyz$y, xyz$z, radius = 0.25, col = COL)
box(col="gray")
dev.off()



#### 7 Populations
library(mapplots)
library(rworldmap)
data(countriesLow)
plot(countriesLow)
coo <- read.table("sampling_data.csv", h = F, stringsAsFactors = F, row.names = NULL, sep = ",")
my_dir <- getwd()
file <- list.files(path=my_dir, pattern="*meanQ", full.names=TRUE, recursive=FALSE)
a <- read.table(file)
gabri <- cbind(a$V1,a$V2,a$V3,a$V4,a$V5,a$V6,a$V7)
gabri <- as.numeric(gabri)
n <- length(a$V1)
gabri_2 <- c(rep("pop1",n), rep("pop2", n), rep("pop3",n),rep("pop4",n),rep("pop5",n),rep("pop6",n),rep("pop7",n))
gabri_2 <- as.factor(gabri_2)
lon <- rep(coo$V7,7)
lat <- rep(coo$V6,7)
# added extra digit to duplicate coordinates to avoid removal of records
xyz <- make.xyz(lon, lat, gabri,gabri_2)
pdf("map.pdf")
plot(countriesLow, xlim= c(min(coo$V7-5),max(coo$V7 + 5)), ylim = c(min(coo$V6-5),max(coo$V6+5)))
COL <- c("#999999", "#E69F00", "#56B4E9", "#009E73","#F0E442", "#0072B2", "#D55E00", "#CC79A7", "black")
draw.pie(xyz$x, xyz$y, xyz$z, radius = 0.35, col = COL)
box(col="gray")
dev.off()



### 8 Populations
library(mapplots)
library(rworldmap)
data(countriesLow)
plot(countriesLow)
coo <- read.table("sampling_data.csv", h = F, stringsAsFactors = F, row.names = NULL, sep = ",")
my_dir <- getwd()
file <- list.files(path=my_dir, pattern="*meanQ", full.names=TRUE, recursive=FALSE)
a <- read.table(file)
gabri <- cbind(a$V1,a$V2,a$V3,a$V4,a$V5,a$V6,a$V7,a$V8)
gabri <- as.numeric(gabri)
n <- length(a$V1)
gabri_2 <- c(rep("pop1",n), rep("pop2", n), rep("pop3",n),rep("pop4",n),rep("pop5",n),rep("pop6",n),rep("pop7",n),rep("pop8",n))
gabri_2 <- as.factor(gabri_2)
lon <- rep(coo$V7,8)
lat <- rep(coo$V6,8)
# added extra digit to duplicate coordinates to avoid removal of records
xyz <- make.xyz(lon, lat, gabri,gabri_2)
pdf("map.pdf")
plot(countriesLow, xlim= c(min(coo$V7-5),max(coo$V7 + 5)), ylim = c(min(coo$V6-5),max(coo$V6+5)))
COL <- c("#999999", "#E69F00", "#56B4E9", "#009E73","#F0E442", "#0072B2", "#D55E00", "#CC79A7", "black")
draw.pie(xyz$x, xyz$y, xyz$z, radius = 0.35, col = COL)
box(col="gray")
dev.off()



### 9 Populations
library(mapplots)
library(rworldmap)
data(countriesLow)
plot(countriesLow)
coo <- read.table("sampling_data.csv", h = F, stringsAsFactors = F, row.names = NULL, sep = ",")
my_dir <- getwd()
file <- list.files(path=my_dir, pattern="*meanQ", full.names=TRUE, recursive=FALSE)
a <- read.table(file)
gabri <- cbind(a$V1,a$V2,a$V3,a$V4,a$V5,a$V6,a$V7,a$V8,a$V9)
gabri <- as.numeric(gabri)
n <- length(a$V1)
gabri_2 <- c(rep("pop1",n), rep("pop2", n), rep("pop3",n),rep("pop4",n),rep("pop5",n),rep("pop6",n),rep("pop7",n),rep("pop8",n),rep("pop9",n))
gabri_2 <- as.factor(gabri_2)
lon <- rep(coo$V7,9)
lat <- rep(coo$V6,9)
# added extra digit to duplicate coordinates to avoid removal of records
xyz <- make.xyz(lon, lat, gabri,gabri_2)
pdf("map.pdf")
plot(countriesLow, xlim= c(min(coo$V7-5),max(coo$V7 + 5)), ylim = c(min(coo$V6-5),max(coo$V6+5)))
COL <- c("#999999", "#E69F00", "#56B4E9", "#009E73","#F0E442", "#0072B2", "#D55E00", "#CC79A7", "black")
draw.pie(xyz$x, xyz$y, xyz$z, radius = 0.35, col = COL)
box(col="gray")
dev.off()



### 10 Populations
library(mapplots)
library(rworldmap)
data(countriesLow)
plot(countriesLow)
coo <- read.table("sampling_data.csv", h = F, stringsAsFactors = F, row.names = NULL, sep = ",")
my_dir <- getwd()
file <- list.files(path=my_dir, pattern="*meanQ", full.names=TRUE, recursive=FALSE)
a <- read.table(file)
gabri <- cbind(a$V1,a$V2,a$V3,a$V4,a$V5,a$V6,a$V7,a$V8,a$V9,a$V10)
gabri <- as.numeric(gabri)
n <- length(a$V1)
gabri_2 <- c(rep("pop1",n), rep("pop2", n), rep("pop3",n),rep("pop4",n),rep("pop5",n),rep("pop6",n),rep("pop7",n),rep("pop8",n),rep("pop9",n),rep("pop10",n))
gabri_2 <- as.factor(gabri_2)
lon <- rep(coo$V7,10)
lat <- rep(coo$V6,1)
# added extra digit to duplicate coordinates to avoid removal of records
xyz <- make.xyz(lon, lat, gabri,gabri_2)
pdf("map.pdf")
plot(countriesLow, xlim= c(min(coo$V7-5),max(coo$V7 + 5)), ylim = c(min(coo$V6-5),max(coo$V6+5)))
COL <- c("#999999", "#E69F00", "#56B4E9", "#009E73","#F0E442", "#0072B2", "#D55E00", "#CC79A7", "black", "brown")
draw.pie(xyz$x, xyz$y, xyz$z, radius = 0.35, col = COL)
box(col="gray")
dev.off()
